language: c

os: linux

sudo: false

addons:
  firefox: latest

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - GECKODRIVER_VERSION=0.20.1
    - GECKODRIVER_DIST=geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
    - GECKODRIVER_SOURCE=https://github.com/mozilla/geckodriver/releases/download
    - MINICONDA_DIST=Miniconda3-4.5.1-Linux-x86_64.sh
    - MINICONDA_SOURCE=https://repo.continuum.io/miniconda
    - CONDA_DIR=$HOME/miniconda3
    - PATH=$CONDA_DIR/bin:$PATH

cache:
  directories:
    - $HOME/.cache/stuff
    - $HOME/.cache/yarn
    - $HOME/.cache/conda

before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
script: ./scripts/travis/test.sh
after_failure: ./scripts/travis/after_failure.sh
before_cache: ./scripts/travis/before_cache.sh
before_deploy: ./scripts/travis/before_deploy.sh

deploy:
  provider: pages
  local-dir: demo
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
